version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5246:5432'
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql